# k8s/ingress.yml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    # This annotation is important for rewriting paths correctly
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # This new line tells the Ingress to use the 'nginx' controller we installed
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*) # Match any path that starts with /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 9000
      - path: /(|/)(.*) # Match the root path and everything else
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80