# k8s/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  # This is your MongoDB URI, Base64 encoded
  MONGO_URI: bW9uZ29kYitzcnY6Ly9yb290OnJvb3RAY2x1c3RlcjAueWRqcGN1ZS5tb25nb2RiLm5ldC9lY29tbWVyY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=

  # This is your JWT Secret, Base64 encoded
  JWT_SECRET: N1coaSQvP1oiKn0vdmkxR0IlUk5jPjk6LkZBe3sqQ0lRdk1Taj5qJElfQm11T3MtOjpYX2h2LX5qYWkpKSFl

